apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server
  name: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  strategy: {}
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - image: 161158265803.dkr.ecr.us-east-1.amazonaws.com/go-server:0.1.0
        name: go-server
        ports:
        - containerPort: 8080
        resources: {}
status: {}
