apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server
  name: go-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: go-server
  type: NodePort
status:
  loadBalancer: {}
